# Generated by Django 2.1.5 on 2019-07-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatus',
            name='type',
            field=models.IntegerField(choices=[(1, 'M'), (2, 'A'), (3, 'N'), (4, 'On Call'), (5, 'Sleap'), (6, 'OFF Day')], default=6),
        ),
    ]
