# Generated by Django 2.1.5 on 2019-07-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_employeestatus_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='workHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakNum', models.IntegerField(default=0)),
                ('one', models.BooleanField(default=True)),
                ('two', models.BooleanField(default=True)),
                ('three', models.BooleanField(default=True)),
                ('four', models.BooleanField(default=True)),
                ('five', models.BooleanField(default=True)),
                ('six', models.BooleanField(default=True)),
                ('seven', models.BooleanField(default=True)),
                ('eight', models.BooleanField(default=True)),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.EmployeeStatus')),
            ],
        ),
    ]
