# Generated by Django 2.2 on 2019-07-09 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_swaprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhours',
            name='status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workhours', to='administration.EmployeeStatus'),
        ),
    ]
