# Generated by Django 2.2 on 2019-07-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20190714_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatus',
            name='called',
            field=models.BooleanField(default=False),
        ),
    ]
