# Generated by Django 2.2 on 2019-07-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_employeestatus_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='admin_request',
            field=models.BooleanField(default=False),
        ),
    ]
