# Generated by Django 2.2 on 2019-07-24 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20190724_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstatus',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='administration.Group'),
        ),
    ]
