# Generated by Django 2.2 on 2019-07-24 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20190724_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='group',
        ),
    ]
