# Generated by Django 2.2 on 2019-07-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_auto_20190724_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.IntegerField(choices=[(1, 'ِACC'), (2, 'APP'), (3, 'ACC supervisor'), (4, 'APP supervisor'), (5, 'Tower supervisor')], default=1),
        ),
    ]
