# Generated by Django 2.2 on 2019-07-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_auto_20190725_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='fullName',
            field=models.CharField(default='hamada', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='phoneNumber',
            field=models.CharField(default='01000000000', max_length=100),
            preserve_default=False,
        ),
    ]
