# Generated by Django 2.2 on 2019-07-26 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_auto_20190725_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('shift', models.IntegerField(choices=[(1, 'M'), (2, 'A'), (3, 'N')])),
                ('text', models.TextField()),
                ('level', models.IntegerField(choices=[(1, 'ACC'), (2, 'APP'), (3, 'ACC supervisor'), (4, 'APP supervisor'), (5, 'Tower supervisor')])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='administration.Employee')),
            ],
        ),
    ]
