# Generated by Django 2.2 on 2019-07-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_auto_20190729_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='all',
            field=models.IntegerField(default=0),
        ),
    ]
