# Generated by Django 2.2 on 2019-08-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_group_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstatus',
            name='brief',
            field=models.TextField(null=True),
        ),
    ]
