# Generated by Django 2.2 on 2019-08-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_employee_certification_admin_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_certification',
            name='prev_start_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='employee_certification',
            name='prev_years',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee_certification',
            name='update',
            field=models.BooleanField(default=False),
        ),
    ]
